### ISSUE TITLE
License Addition

### ISSUE THREAD

**Issue by serinuntius** [virapture/firebase-monorepo-template#6]
Hello,

Could we please add a license to this repository? I noticed that the `package.json` mentions MIT. Can we confirm that the entire codebase is intended to be under the MIT License?

https://github.com/virapture/firebase-monorepo-template/blob/f271b3696764cfd84db0962e4a456f24df8e6e5f/package.json#L40

Thank you.

**Comment by mogmet** [comment]
This template is made entirely with OSS.
so, no problem.

**Comment by serinuntius** [comment]
Thanks
